apiVersion: v1
stringData:
gi  MONGODB_URL: 'mongodb://gm6vx_gtfs:zCGp9*ghPmt#ezFjdrqo6nyI@mongo-gtfs-mongodb:27017/gtfseditor'
  JWT_SECRET: 'thisisasamplesecret'
kind: secret
metadata:
  name: custom-envs
type: Opaque
